server:
   port: 8099

eureka:
  client:
    #registerWithEureka: false
    serviceUrl:
      defaultZone: http://eureka-serverv1:8761/eureka/ 

spring:
  application:
    name: servicio-zuul-server
zuul:
  host:
    connect-timeout-millis: 100000
    socket-timeout-millis: 100000
  routes:         
    bancarios:
      path: /micro-bancario/**
      service-id: micro-bancario
    creditos:
      path: /micro-credito/**
      service-id: micro-credito
    clientes:
      path: /micro-clientes/**
      service-id: micro-clientes
    operacionesbancarias:
      path: /micro-operacionesbancarias/**
      service-id: micro-operacionesbancarias
    operacionescredito:
      path: /micro-operacionescreditos/**
      service-id: micro-operacionescreditos
      
    
    
    
    
    
    
  # localhost:8080/pacientes
  # localhost:8099/micro-crud/pacientes
    